// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine9.3

#ifndef UI_SCREENTABLE_H
#define UI_SCREENTABLE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenTable
extern void ui_ScreenTable_screen_init(void);
extern void ui_ScreenTable_screen_destroy(void);
extern lv_obj_t * ui_ScreenTable;
extern lv_obj_t * ui_BlockHeader2;
extern lv_obj_t * ui_TimeTitle2;
extern lv_obj_t * ui_DataContainerMotor;
extern lv_obj_t * ui_StateContainer;
extern lv_obj_t * ui_StateLabel;
extern lv_obj_t * ui_StateValue;
extern lv_obj_t * ui_SpeedContainer;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_ISContainer;
extern lv_obj_t * ui_ISLabel;
extern lv_obj_t * ui_ISValue;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenTable;
extern lv_obj_t * uic_DataContainerMotor;
extern lv_obj_t * uic_StateContainer;
extern lv_obj_t * uic_StateLabel;
extern lv_obj_t * uic_SpeedContainer;
extern lv_obj_t * uic_SpeedLabel;
extern lv_obj_t * uic_SpeedValue;
extern lv_obj_t * uic_ISContainer;
extern lv_obj_t * uic_ISLabel;
extern lv_obj_t * uic_ISValue;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

