// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine9.3

#ifndef UI_SCREENWEATHER_H
#define UI_SCREENWEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWeather
extern void ui_ScreenWeather_screen_init(void);
extern void ui_ScreenWeather_screen_destroy(void);
extern lv_obj_t * ui_ScreenWeather;
extern lv_obj_t * ui_BlockHeader;
extern lv_obj_t * ui_btn;
extern lv_obj_t * ui_NameCity;
extern lv_obj_t * ui_TimeTitle;
extern lv_obj_t * ui_BlockWeatherIcon;
extern lv_obj_t * ui_ImageWeather;
extern lv_obj_t * ui_WeatherTitle;
extern lv_obj_t * ui_TemperatureTitle;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenWeather;
extern lv_obj_t * uic_BlockHeader;
extern lv_obj_t * uic_btn;
extern lv_obj_t * uic_NameCity;
extern lv_obj_t * uic_TimeTitle;
extern lv_obj_t * uic_BlockWeatherIcon;
extern lv_obj_t * uic_ImageWeather;
extern lv_obj_t * uic_WeatherTitle;
extern lv_obj_t * uic_TemperatureTitle;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

