// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine9.3

#include "ui.h"

lv_obj_t * uic_ISValue;
lv_obj_t * uic_ISLabel;
lv_obj_t * uic_ISContainer;
lv_obj_t * uic_SpeedValue;
lv_obj_t * uic_SpeedLabel;
lv_obj_t * uic_SpeedContainer;
lv_obj_t * uic_StateLabel;
lv_obj_t * uic_StateContainer;
lv_obj_t * uic_DataContainerMotor;
lv_obj_t * uic_ScreenTable;
lv_obj_t * ui_ScreenTable = NULL;
lv_obj_t * ui_BlockHeader2 = NULL;
lv_obj_t * ui_TimeTitle2 = NULL;
lv_obj_t * ui_DataContainerMotor = NULL;
lv_obj_t * ui_StateContainer = NULL;
lv_obj_t * ui_StateLabel = NULL;
lv_obj_t * ui_StateValue = NULL;
lv_obj_t * ui_SpeedContainer = NULL;
lv_obj_t * ui_SpeedLabel = NULL;
lv_obj_t * ui_SpeedValue = NULL;
lv_obj_t * ui_ISContainer = NULL;
lv_obj_t * ui_ISLabel = NULL;
lv_obj_t * ui_ISValue = NULL;
// event funtions

// build funtions

void ui_ScreenTable_screen_init(void)
{
    ui_ScreenTable = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenTable, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ScreenTable, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ScreenTable, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_BlockHeader2 = lv_obj_create(ui_ScreenTable);
    lv_obj_remove_style_all(ui_BlockHeader2);
    lv_obj_set_height(ui_BlockHeader2, 25);
    lv_obj_set_width(ui_BlockHeader2, lv_pct(85));
    lv_obj_set_x(ui_BlockHeader2, 0);
    lv_obj_set_y(ui_BlockHeader2, 15);
    lv_obj_set_align(ui_BlockHeader2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_BlockHeader2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BlockHeader2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BlockHeader2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeTitle2 = lv_label_create(ui_BlockHeader2);
    lv_obj_set_width(ui_TimeTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeTitle2, -20);
    lv_obj_set_y(ui_TimeTitle2, 20);
    lv_obj_set_align(ui_TimeTitle2, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_TimeTitle2, "12:20");
    ui_object_set_themeable_style_property(ui_TimeTitle2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_TimeTitle2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);
    lv_obj_set_style_text_font(ui_TimeTitle2, &ui_font_Geologica16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DataContainerMotor = lv_obj_create(ui_ScreenTable);
    lv_obj_remove_style_all(ui_DataContainerMotor);
    lv_obj_set_width(ui_DataContainerMotor, lv_pct(95));
    lv_obj_set_height(ui_DataContainerMotor, lv_pct(50));
    lv_obj_set_align(ui_DataContainerMotor, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DataContainerMotor, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DataContainerMotor, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_DataContainerMotor, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StateContainer = lv_obj_create(ui_DataContainerMotor);
    lv_obj_remove_style_all(ui_StateContainer);
    lv_obj_set_width(ui_StateContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_StateContainer, 1);
    lv_obj_set_align(ui_StateContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StateContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_StateContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_StateContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StateLabel = lv_label_create(ui_StateContainer);
    lv_obj_set_width(ui_StateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateLabel, "State:");
    ui_object_set_themeable_style_property(ui_StateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_StateLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);

    ui_StateValue = lv_label_create(ui_StateContainer);
    lv_obj_set_width(ui_StateValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StateValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateValue, "unknown");
    ui_object_set_themeable_style_property(ui_StateValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_StateValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);

    ui_SpeedContainer = lv_obj_create(ui_DataContainerMotor);
    lv_obj_remove_style_all(ui_SpeedContainer);
    lv_obj_set_width(ui_SpeedContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_SpeedContainer, 1);
    lv_obj_set_align(ui_SpeedContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SpeedContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SpeedContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SpeedContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpeedLabel = lv_label_create(ui_SpeedContainer);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel, "Speed:");
    ui_object_set_themeable_style_property(ui_SpeedLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_SpeedLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);

    ui_SpeedValue = lv_label_create(ui_SpeedContainer);
    lv_obj_set_width(ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue, "0");
    ui_object_set_themeable_style_property(ui_SpeedValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_SpeedValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);

    ui_ISContainer = lv_obj_create(ui_DataContainerMotor);
    lv_obj_remove_style_all(ui_ISContainer);
    lv_obj_set_width(ui_ISContainer, lv_pct(100));
    lv_obj_set_flex_grow(ui_ISContainer, 1);
    lv_obj_set_align(ui_ISContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ISContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ISContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ISContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ISLabel = lv_label_create(ui_ISContainer);
    lv_obj_set_width(ui_ISLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ISLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ISLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ISLabel, "IS:");
    ui_object_set_themeable_style_property(ui_ISLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_ISLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);

    ui_ISValue = lv_label_create(ui_ISContainer);
    lv_obj_set_width(ui_ISValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ISValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ISValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ISValue, "0");
    ui_object_set_themeable_style_property(ui_ISValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_ISValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);

    uic_ScreenTable = ui_ScreenTable;
    uic_DataContainerMotor = ui_DataContainerMotor;
    uic_StateContainer = ui_StateContainer;
    uic_StateLabel = ui_StateLabel;
    uic_SpeedContainer = ui_SpeedContainer;
    uic_SpeedLabel = ui_SpeedLabel;
    uic_SpeedValue = ui_SpeedValue;
    uic_ISContainer = ui_ISContainer;
    uic_ISLabel = ui_ISLabel;
    uic_ISValue = ui_ISValue;

}

void ui_ScreenTable_screen_destroy(void)
{
    if(ui_ScreenTable) lv_obj_del(ui_ScreenTable);

    // NULL screen variables
    uic_ScreenTable = NULL;
    ui_ScreenTable = NULL;
    ui_BlockHeader2 = NULL;
    ui_TimeTitle2 = NULL;
    uic_DataContainerMotor = NULL;
    ui_DataContainerMotor = NULL;
    uic_StateContainer = NULL;
    ui_StateContainer = NULL;
    uic_StateLabel = NULL;
    ui_StateLabel = NULL;
    ui_StateValue = NULL;
    uic_SpeedContainer = NULL;
    ui_SpeedContainer = NULL;
    uic_SpeedLabel = NULL;
    ui_SpeedLabel = NULL;
    uic_SpeedValue = NULL;
    ui_SpeedValue = NULL;
    uic_ISContainer = NULL;
    ui_ISContainer = NULL;
    uic_ISLabel = NULL;
    ui_ISLabel = NULL;
    uic_ISValue = NULL;
    ui_ISValue = NULL;

}
