// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine9.3

#include "ui.h"

lv_obj_t * uic_TemperatureTitle;
lv_obj_t * uic_WeatherTitle;
lv_obj_t * uic_ImageWeather;
lv_obj_t * uic_BlockWeatherIcon;
lv_obj_t * uic_TimeTitle;
lv_obj_t * uic_NameCity;
lv_obj_t * uic_btn;
lv_obj_t * uic_BlockHeader;
lv_obj_t * uic_Screen;
lv_obj_t * ui_Screen = NULL;
lv_obj_t * ui_BlockHeader = NULL;
lv_obj_t * ui_btn = NULL;
lv_obj_t * ui_NameCity = NULL;
lv_obj_t * ui_TimeTitle = NULL;
lv_obj_t * ui_BlockWeatherIcon = NULL;
lv_obj_t * ui_ImageWeather = NULL;
lv_obj_t * ui_WeatherTitle = NULL;
lv_obj_t * ui_TemperatureTitle = NULL;
// event funtions

// build funtions

void ui_Screen_screen_init(void)
{
    ui_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_Screen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_BlockHeader = lv_obj_create(ui_Screen);
    lv_obj_remove_style_all(ui_BlockHeader);
    lv_obj_set_height(ui_BlockHeader, 25);
    lv_obj_set_width(ui_BlockHeader, lv_pct(85));
    lv_obj_set_x(ui_BlockHeader, 0);
    lv_obj_set_y(ui_BlockHeader, 15);
    lv_obj_set_align(ui_BlockHeader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_BlockHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BlockHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BlockHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn = lv_button_create(ui_BlockHeader);
    lv_obj_set_height(ui_btn, 25);
    lv_obj_set_width(ui_btn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_btn, 20);
    lv_obj_set_y(ui_btn, 20);
    lv_obj_set_flex_flow(ui_btn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btn, lv_color_hex(0x7D7D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_btn, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NameCity = lv_label_create(ui_btn);
    lv_obj_set_width(ui_NameCity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NameCity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NameCity, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_NameCity, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_NameCity, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_long_mode(ui_NameCity, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_NameCity, "Кемерово1 Кемерово2 Кемерово3 Кемерово4");
    ui_object_set_themeable_style_property(ui_NameCity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_NameCity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);
    lv_obj_set_style_text_align(ui_NameCity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NameCity, &ui_font_Geologica14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_NameCity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_NameCity, 140, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeTitle = lv_label_create(ui_BlockHeader);
    lv_obj_set_width(ui_TimeTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeTitle, -20);
    lv_obj_set_y(ui_TimeTitle, 20);
    lv_obj_set_align(ui_TimeTitle, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_TimeTitle, "");
    ui_object_set_themeable_style_property(ui_TimeTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_TimeTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);
    lv_obj_set_style_text_font(ui_TimeTitle, &ui_font_Geologica16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlockWeatherIcon = lv_obj_create(ui_Screen);
    lv_obj_remove_style_all(ui_BlockWeatherIcon);
    lv_obj_set_width(ui_BlockWeatherIcon, 240);
    lv_obj_set_height(ui_BlockWeatherIcon, 150);
    lv_obj_set_x(ui_BlockWeatherIcon, 0);
    lv_obj_set_y(ui_BlockWeatherIcon, -35);
    lv_obj_set_align(ui_BlockWeatherIcon, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BlockWeatherIcon, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BlockWeatherIcon, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BlockWeatherIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BlockWeatherIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlockWeatherIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageWeather = lv_image_create(ui_BlockWeatherIcon);
    lv_image_set_src(ui_ImageWeather, &ui_img_0_png);
    lv_obj_set_width(ui_ImageWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWeather, 13);
    lv_obj_set_y(ui_ImageWeather, -43);
    lv_obj_set_align(ui_ImageWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeather, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherTitle = lv_label_create(ui_BlockWeatherIcon);
    lv_obj_set_width(ui_WeatherTitle, lv_pct(100));
    lv_obj_set_height(ui_WeatherTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherTitle, 0);
    lv_obj_set_y(ui_WeatherTitle, 33);
    lv_obj_set_align(ui_WeatherTitle, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_WeatherTitle, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_WeatherTitle, "Облачная");
    ui_object_set_themeable_style_property(ui_WeatherTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_WeatherTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);
    lv_obj_set_style_text_align(ui_WeatherTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WeatherTitle, &ui_font_Geologica16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TemperatureTitle = lv_label_create(ui_Screen);
    lv_obj_set_width(ui_TemperatureTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TemperatureTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TemperatureTitle, -15);
    lv_obj_set_y(ui_TemperatureTitle, -15);
    lv_obj_set_align(ui_TemperatureTitle, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_TemperatureTitle, "-16");
    ui_object_set_themeable_style_property(ui_TemperatureTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_foreground);
    ui_object_set_themeable_style_property(ui_TemperatureTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_foreground);
    lv_obj_set_style_text_font(ui_TemperatureTitle, &ui_font_Geologica64, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Screen = ui_Screen;
    uic_BlockHeader = ui_BlockHeader;
    uic_btn = ui_btn;
    uic_NameCity = ui_NameCity;
    uic_TimeTitle = ui_TimeTitle;
    uic_BlockWeatherIcon = ui_BlockWeatherIcon;
    uic_ImageWeather = ui_ImageWeather;
    uic_WeatherTitle = ui_WeatherTitle;
    uic_TemperatureTitle = ui_TemperatureTitle;

}

void ui_Screen_screen_destroy(void)
{
    if(ui_Screen) lv_obj_del(ui_Screen);

    // NULL screen variables
    uic_Screen = NULL;
    ui_Screen = NULL;
    uic_BlockHeader = NULL;
    ui_BlockHeader = NULL;
    uic_btn = NULL;
    ui_btn = NULL;
    uic_NameCity = NULL;
    ui_NameCity = NULL;
    uic_TimeTitle = NULL;
    ui_TimeTitle = NULL;
    uic_BlockWeatherIcon = NULL;
    ui_BlockWeatherIcon = NULL;
    uic_ImageWeather = NULL;
    ui_ImageWeather = NULL;
    uic_WeatherTitle = NULL;
    ui_WeatherTitle = NULL;
    uic_TemperatureTitle = NULL;
    ui_TemperatureTitle = NULL;

}
