// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SquareLine9.3

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_background[3] = {0x000000, 0x000000, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_background[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_foreground[3] = {0xFFFFFF, 0xFFFFFF, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_foreground[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DARK;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

